// Generated by gencpp from file path_planning_msg/pp_msgRequest.msg
// DO NOT EDIT!


#ifndef PATH_PLANNING_MSG_MESSAGE_PP_MSGREQUEST_H
#define PATH_PLANNING_MSG_MESSAGE_PP_MSGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_planning_msg
{
template <class ContainerAllocator>
struct pp_msgRequest_
{
  typedef pp_msgRequest_<ContainerAllocator> Type;

  pp_msgRequest_()
    : costmap()
    , width(0)
    , height(0)
    , start(0)
    , goal(0)  {
    }
  pp_msgRequest_(const ContainerAllocator& _alloc)
    : costmap(_alloc)
    , width(0)
    , height(0)
    , start(0)
    , goal(0)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _costmap_type;
  _costmap_type costmap;

   typedef int32_t _width_type;
  _width_type width;

   typedef int32_t _height_type;
  _height_type height;

   typedef int32_t _start_type;
  _start_type start;

   typedef int32_t _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::path_planning_msg::pp_msgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_planning_msg::pp_msgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pp_msgRequest_

typedef ::path_planning_msg::pp_msgRequest_<std::allocator<void> > pp_msgRequest;

typedef boost::shared_ptr< ::path_planning_msg::pp_msgRequest > pp_msgRequestPtr;
typedef boost::shared_ptr< ::path_planning_msg::pp_msgRequest const> pp_msgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_planning_msg::pp_msgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_planning_msg::pp_msgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_planning_msg::pp_msgRequest_<ContainerAllocator1> & lhs, const ::path_planning_msg::pp_msgRequest_<ContainerAllocator2> & rhs)
{
  return lhs.costmap == rhs.costmap &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.start == rhs.start &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_planning_msg::pp_msgRequest_<ContainerAllocator1> & lhs, const ::path_planning_msg::pp_msgRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_planning_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::path_planning_msg::pp_msgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_planning_msg::pp_msgRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planning_msg::pp_msgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planning_msg::pp_msgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planning_msg::pp_msgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planning_msg::pp_msgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_planning_msg::pp_msgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e514377e8f86e4f45692a0dfbaeeeb2a";
  }

  static const char* value(const ::path_planning_msg::pp_msgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe514377e8f86e4f4ULL;
  static const uint64_t static_value2 = 0x5692a0dfbaeeeb2aULL;
};

template<class ContainerAllocator>
struct DataType< ::path_planning_msg::pp_msgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_planning_msg/pp_msgRequest";
  }

  static const char* value(const ::path_planning_msg::pp_msgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_planning_msg::pp_msgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] costmap\n"
"int32 width\n"
"int32 height\n"
"int32 start\n"
"int32 goal \n"
;
  }

  static const char* value(const ::path_planning_msg::pp_msgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_planning_msg::pp_msgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.costmap);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.start);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pp_msgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_planning_msg::pp_msgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_planning_msg::pp_msgRequest_<ContainerAllocator>& v)
  {
    s << indent << "costmap[]" << std::endl;
    for (size_t i = 0; i < v.costmap.size(); ++i)
    {
      s << indent << "  costmap[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.costmap[i]);
    }
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "start: ";
    Printer<int32_t>::stream(s, indent + "  ", v.start);
    s << indent << "goal: ";
    Printer<int32_t>::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_PLANNING_MSG_MESSAGE_PP_MSGREQUEST_H
