// Generated by gencpp from file path_planning_msg/pp_msg.msg
// DO NOT EDIT!


#ifndef PATH_PLANNING_MSG_MESSAGE_PP_MSG_H
#define PATH_PLANNING_MSG_MESSAGE_PP_MSG_H

#include <ros/service_traits.h>


#include <path_planning_msg/pp_msgRequest.h>
#include <path_planning_msg/pp_msgResponse.h>


namespace path_planning_msg
{

struct pp_msg
{

typedef pp_msgRequest Request;
typedef pp_msgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pp_msg
} // namespace path_planning_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_planning_msg::pp_msg > {
  static const char* value()
  {
    return "b6b0dc4949ce8f317d462fa1f43060e0";
  }

  static const char* value(const ::path_planning_msg::pp_msg&) { return value(); }
};

template<>
struct DataType< ::path_planning_msg::pp_msg > {
  static const char* value()
  {
    return "path_planning_msg/pp_msg";
  }

  static const char* value(const ::path_planning_msg::pp_msg&) { return value(); }
};


// service_traits::MD5Sum< ::path_planning_msg::pp_msgRequest> should match
// service_traits::MD5Sum< ::path_planning_msg::pp_msg >
template<>
struct MD5Sum< ::path_planning_msg::pp_msgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_planning_msg::pp_msg >::value();
  }
  static const char* value(const ::path_planning_msg::pp_msgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planning_msg::pp_msgRequest> should match
// service_traits::DataType< ::path_planning_msg::pp_msg >
template<>
struct DataType< ::path_planning_msg::pp_msgRequest>
{
  static const char* value()
  {
    return DataType< ::path_planning_msg::pp_msg >::value();
  }
  static const char* value(const ::path_planning_msg::pp_msgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_planning_msg::pp_msgResponse> should match
// service_traits::MD5Sum< ::path_planning_msg::pp_msg >
template<>
struct MD5Sum< ::path_planning_msg::pp_msgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_planning_msg::pp_msg >::value();
  }
  static const char* value(const ::path_planning_msg::pp_msgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planning_msg::pp_msgResponse> should match
// service_traits::DataType< ::path_planning_msg::pp_msg >
template<>
struct DataType< ::path_planning_msg::pp_msgResponse>
{
  static const char* value()
  {
    return DataType< ::path_planning_msg::pp_msg >::value();
  }
  static const char* value(const ::path_planning_msg::pp_msgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_PLANNING_MSG_MESSAGE_PP_MSG_H
